name = "personal-website"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2023-01-22"

compatibility_flags = ["nodejs_als"]

[vars]
NODE_VERSION = "21"

[env.production]
compatibility_date = "2023-01-22"

[env.production.vars]
NODE_VERSION = "21"
